sleeper_base_url: https://api.sleeper.app/v1
espn_start_year: 2013
espn_end_year: 2018

args:
  - definition: league_name
    params:
      help: The unique name of this league

  - definition: sleeper_season_id
    params:
      help: The league ID of the most recent Sleeper season

  - definition: gcs_bucket
    params:
      help: The Google Cloud Storage Bucket ID

  - definition: gbq_project
    params:
      help: The Google BigQuery Project ID

  - definition: gbq_dataset
    params:
      help: The Google BigQuery dataset to output tables to

  - definition:
      - -e
      - --espn-league-id
    params:
      help: The ESPN league ID

  - definition:
      - -s
      - --espn-s2
    params:
      help: The espn_s2 cookie

  - definition:
      - -w
      - --espn-swid
    params:
      help: The ESPN swid cookie

  - definition:
      - -l
      - --log-level
    params:
      default: INFO
      help: A python logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

tables:
  sleeper:
    seasons:
      method: get_season
      key_map:
        league_name:
          data_type: STRING
        league_id:
          data_type: STRING
          col_name: season_id
        season:
          data_type: INT64
          col_name: year
        draft_id:
          data_type: STRING
        previous_league_id:
          data_type: STRING
          col_name: previous_season_id
        settings:
          start_week:
            data_type: INT64
          playoff_week_start:
            data_type: INT64
            col_name: playoff_start_week
          last_scored_leg:
            data_type: INT64
            col_name: last_completed_week
          league_average_match:
            data_type: INT64
            col_name: has_matchup_against_median
          playoff_teams:
            data_type: INT64
            col_name: playoff_team_count
    draft_picks:
      method: get_draft_picks
      key_map:
        season_id:
          data_type: STRING
        draft_id:
          data_type: STRING
          col_name: draft_id
        pick_no:
          data_type: INT64
          col_name: pick_num
        round:
          data_type: INT64
          col_name: round_num
        draft_slot:
          data_type: INT64
        player_id:
          data_type: STRING
        roster_id:
          data_type: INT64
        picked_by:
          data_type: STRING
          col_name: user_id
        is_keeper:
          data_type: INT64
        metadata:
          first_name:
            data_type: STRING
          last_name:
            data_type: STRING
          position:
            data_type: STRING
          team:
            data_type: STRING
          years_exp:
            data_type: STRING
          status:
            data_type: STRING
          injury_status:
            data_type: STRING
    rosters:
      method: get_rosters
      key_map:
        season_id:
          data_type: STRING
        roster_id:
          data_type: INT64
          col_name: roster_id
        owner_id:
          data_type: STRING
          col_name: user_id
    lookup_playoffs:
      method: get_winners_bracket
      key_map:
        season_id:
          data_type: STRING
        r:
          data_type: INT64
          col_name: bracket_round
        p:
          data_type: INT64
          col_name: winner_place
        t1:
          data_type: INT64
          col_name: roster_id_a
        t2:
          data_type: INT64
          col_name: roster_id_b
        w:
          data_type: INT64
          col_name: roster_id_winner
        l:
          data_type: INT64
          col_name: roster_id_loser
    matchups:
      method: get_matchups
      key_map:
        season_id:
          data_type: STRING
        week:
          data_type: INT64
        matchup_id:
          data_type: INT64
        roster_id:
          data_type: INT64
        points:
          data_type: FLOAT64
        custom_points:
          data_type: FLOAT64
    user_seasons:
      method: get_users
      key_map:
        season_id:
          data_type: STRING
        user_id:
          data_type: STRING
        display_name:
          data_type: STRING
  espn:
    seasons:
      method: get_season
      key_map:
        league_name:
          data_type: STRING
        league_id:
          data_type: STRING
        year:
          data_type: INT64
        season_id:
          data_type: STRING
        firstScoringPeriod:
          data_type: INT64
          col_name: start_week
        currentMatchupPeriod:
          data_type: INT64
          col_name: current_week
        settings:
          reg_season_count:
            data_type: INT64
            col_name: regular_season_weeks
          team_count:
            data_type: INT64
          playoff_team_count:
            data_type: INT64
    draft_picks:
      method: get_draft_picks
      key_map:
        season_id:
          data_type: STRING
        playerId:
          data_type: INT64
          col_name: player_id
        playerName:
          data_type: STRING
          col_name: player_name
        position:
          data_type: STRING
        round_num:
          data_type: INT64
        round_pick:
          data_type: INT64
        bid_amount:
          data_type: INT64
        keeper_status:
          data_type: INT64
          col_name: is_keeper
        team:
          team_id:
            data_type: INT64
    teams:
      method: get_teams
      key_map:
        season_id:
          data_type: STRING
        team_id:
          data_type: INT64
        owner:
          data_type: STRING
          col_name: manager
        wins:
          data_type: INT64
        losses:
          data_type: INT64
        standing:
          data_type: INT64
        final_standing:
          data_type: INT64
        points_for:
          data_type: FLOAT64
          col_name: points_regular_season
        points_against:
          data_type: FLOAT64
          col_name: points_against_regular_season
    matchups:
      method: get_matchups
      key_map:
        season_id:
          data_type: STRING
        team_id:
          data_type: INT64
        schedule:
          data_type: INT64
          col_name: opponent_id
        scores:
          data_type: FLOAT64
          col_name: points
        mov:
          data_type: FLOAT64
          col_name: margin_of_victory
        week:
          data_type: INT64
