name: Refresh
on:
  schedule:
    - cron: '0 9 * 8-12,1 3'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Google Application Credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GBQ_PROJECT }}
          service_account_key: ${{ secrets.APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Refresh data
        env:
          LEAGUE_NAME: ${{ secrets.LEAGUE_NAME }}
          SLEEPER_SEASON_ID: ${{ secrets.SLEEPER_SEASON_ID }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GBQ_PROJECT: ${{ secrets.GBQ_PROJECT }}
          GBQ_DATASET: ${{ secrets.GBQ_DATASET }}
        run: |
          python main.py $LEAGUE_NAME $SLEEPER_SEASON_ID $GCS_BUCKET $GBQ_PROJECT $GBQ_DATASET