name: Refresh
on:
  schedule:
    - cron: '0 9 * 8-12,1 3'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.APPLICATION_CREDENTIALS }}
      
      - name: Set up Google Application Credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GBQ_PROJECT }}

      - name: Refresh data
        env:
          LEAGUE_NAME: ${{ secrets.LEAGUE_NAME }}
          SLEEPER_SEASON_ID: ${{ secrets.SLEEPER_SEASON_ID }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GBQ_PROJECT: ${{ secrets.GBQ_PROJECT }}
          GBQ_DATASET: ${{ secrets.GBQ_DATASET }}
        run: |
          python main.py $LEAGUE_NAME $SLEEPER_SEASON_ID $GCS_BUCKET $GBQ_PROJECT $GBQ_DATASET
